
import okio.buffer
import okio.sink
import org.gradle.api.DefaultTask
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.ListProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction

abstract class GenerateSrcTask : DefaultTask() {
    @get:OutputFile
    abstract val file: RegularFileProperty

    @get:Input
    abstract val packageName: Property<String>

    @get:Input
    abstract val imports: ListProperty<String>

    private var writerAction: (StringAppendable.() -> Unit)? = null

    fun content(action: (StringAppendable.() -> Unit)) {
        writerAction = action
    }

    init {
        file.convention(
            this.project.fastutilGeneratorOutput
                .map { it.file(this.name + ".kt") },
        )
    }

    @TaskAction
    fun generate() {
        val file = file.get().asFile
        file.parentFile.mkdirs()
        file.sink().buffer().use { sink ->
            val appendable = StringAppendable(sink::writeUtf8)

            appendable.appendLine("// Generated by task ${this.name}")
            appendable.appendLine("""@file:Suppress("unused", "NOTHING_TO_INLINE")""")
            appendable.appendLine("""@file:JvmName("${file.nameWithoutExtension}")""")
            appendable.appendLine("package ${packageName.get()}")
            appendable.appendLine()

            imports.get().forEach { import ->
                appendable.appendLine("import $import")
            }

            appendable.appendLine()
            writerAction?.invoke(appendable)
        }
    }
}
